# Generated by Django 5.2.6 on 2026-09-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price_tier', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-range'), ('premium', 'Premium')], default='mid', max_length=10)),
                ('size', models.CharField(choices=[('solo', 'Solo / founder-only'), ('micro', '2-9 people'), ('small', '10-49 people'), ('medium', '50-249 people')], default='micro', max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, help_text='State / province', max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=60)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('open_to_partnerships', models.BooleanField(default=True)),
                ('partnership_pitch', models.TextField(blank=True, help_text='What kind of collaboration are you looking for?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_tags', models.ManyToManyField(blank=True, related_name='businesses', to='catalog.audiencetag')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='catalog.category')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ('name',),
            },
        ),
    ]
