# Generated by Django 5.2.6 on 2026-09-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='businesses.business')),
                ('to_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='businesses.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_a', to='businesses.business')),
                ('business_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to='businesses.business')),
                ('source_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partnershiprequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='partnershiprequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_business', models.F('to_business')), _negated=True), name='partnership_request_not_self'),
        ),
        migrations.AddConstraint(
            model_name='partnershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_business', 'to_business'), name='one_pending_request_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('business_a', 'business_b'), name='unique_connection_pair'),
        ),
    ]
